#ifndef OXC_TRANSFORMER_H
#define OXC_TRANSFORMER_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum {
    /// Success
    oxcc_transpile_result_ok = 0,
    /// Provided arguments are not valid
    oxcc_transpile_result_invalid,
    /// An error occurred with I/O
    oxcc_transpile_result_io,
    /// Unable to parse the source
    oxcc_transpile_result_parse,
    /// Semantic issue with the source
    oxcc_transpile_result_semantic,
    /// Unable to transpile the source
    oxcc_transpile_result_transformer,
} oxcc_transpile_result;

/// # Safety
/// Don't free the returned pointer with gnu malloc/free, instead use `oxcc_free`.
/// Also the returned pointer can be NULL.
oxcc_transpile_result oxcc__transpile(const char *path_ptr,
                                      size_t path_len,
                                      const char **output_ptr,
                                      size_t *output_len);

/// # Safety
/// Make sure you pass in a pointer to a string allocated by `demo_transpile`
void oxcc__free(const char *input);

#endif  /* OXC_TRANSFORMER_H */
